const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

export interface LoginCredentials {
  username: string;
  password: string;
}

export interface AuthResponse {
  access_token: string;
  id_token: string;
  refresh_token: string;
  token_type: string;
  expires_in: number;
}

export interface User {
  username: string;
  email: string;
  sub?: string;
}

export interface ImageMetadata {
  key: string;
  url: string; // Mapped from presigned_url
  size: number;
  last_modified: string;
  content_type?: string;
  metadata?: {
    original_filename?: string;
    uploaded_by?: string;
    upload_date?: string;
  };
}

// Backend response format (before transformation)
interface BackendImageMetadata {
  key: string;
  presigned_url: string;
  size: number;
  last_modified: string;
  content_type?: string;
  metadata?: {
    original_filename?: string;
    uploaded_by?: string;
    upload_date?: string;
  };
}

export interface ListImagesResponse {
  images: ImageMetadata[];
  count: number;
}

export interface UploadResponse {
  key: string;
  message: string;
  success?: boolean;
  customer_id?: string | null;
  folder?: string;
}

export interface DeleteResponse {
  message: string;
}

// Customer Management Types
export interface CustomerProfile {
  customer_id: string;
  email: string;
  name: string;
  phone_number?: string;
  customer_folder: string;
  created_date: string;
  enabled: boolean;
  temporary_password?: string; // Returned only on customer creation
  user_status?: string; // Cognito user status: FORCE_CHANGE_PASSWORD, CONFIRMED, etc.
}

export interface CreateCustomerRequest {
  email: string;
  name: string;
  phone_number?: string;
  // Note: temporary_password is auto-generated by the API and returned in response
}

export interface UpdateCustomerRequest {
  name?: string;
  phone_number?: string;
  enabled?: boolean;
}

export interface CustomerListResponse {
  customers: CustomerProfile[];
  count: number;
}

class ApiClient {
  private getAuthHeader(): HeadersInit {
    const token = localStorage.getItem('access_token');
    if (!token) {
      return {};
    }
    return {
      Authorization: `Bearer ${token}`,
    };
  }

  // Helper to add timeout to fetch requests
  private async fetchWithTimeout(url: string, options: RequestInit = {}, timeoutMs: number = 15000): Promise<Response> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), timeoutMs);

    try {
      const response = await fetch(url, {
        ...options,
        signal: controller.signal,
      });
      clearTimeout(timeout);
      return response;
    } catch (error) {
      clearTimeout(timeout);
      if (error instanceof Error && error.name === 'AbortError') {
        throw new Error('Request timeout - please check your connection');
      }
      throw error;
    }
  }

  async login(credentials: LoginCredentials): Promise<AuthResponse> {
    const response = await fetch(`${API_URL}/auth/login`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(credentials),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Login failed' }));
      throw new Error(error.detail || 'Login failed');
    }

    return response.json();
  }

  async refreshToken(refreshToken: string): Promise<AuthResponse> {
    const response = await fetch(`${API_URL}/auth/refresh`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ refresh_token: refreshToken }),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Token refresh failed' }));
      throw new Error(error.detail || 'Token refresh failed');
    }

    return response.json();
  }

  async changePassword(data: { old_password: string; new_password: string }): Promise<{ message: string }> {
    console.log('🔐 Changing password...');

    try {
      const response = await this.fetchWithTimeout(`${API_URL}/auth/change-password`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...this.getAuthHeader(),
        },
        body: JSON.stringify(data),
      }, 15000);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to change password' }));
        throw new Error(error.detail || 'Failed to change password');
      }

      return response.json();
    } catch (error) {
      console.error('❌ Change password error:', error);
      throw error;
    }
  }

  async updateProfile(data: { full_name?: string; phone_number?: string }): Promise<{ message: string }> {
    console.log('📝 Updating profile...');
    console.log('📦 Profile data:', data);

    // Check if token exists
    const token = localStorage.getItem('access_token');
    console.log('🔑 Token exists:', !!token);
    console.log('🔑 Token preview:', token ? `${token.substring(0, 20)}...` : 'NO TOKEN');

    try {
      const headers = {
        'Content-Type': 'application/json',
        ...this.getAuthHeader(),
      };
      console.log('📋 Request headers:', Object.keys(headers));

      const response = await this.fetchWithTimeout(`${API_URL}/auth/profile`, {
        method: 'PUT',
        headers: headers,
        body: JSON.stringify(data),
      }, 15000);

      console.log('📡 Response status:', response.status);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to update profile' }));
        console.error('❌ Response error:', error);
        throw new Error(error.detail || 'Failed to update profile');
      }

      const result = await response.json();
      console.log('✅ Profile update successful:', result);
      return result;
    } catch (error) {
      console.error('❌ Update profile error:', error);
      throw error;
    }
  }

  async forgotPassword(username: string): Promise<{ message: string }> {
    console.log('🔑 Initiating forgot password...');

    try {
      const response = await this.fetchWithTimeout(`${API_URL}/auth/forgot-password`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ username }),
      }, 15000);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to initiate password reset' }));
        throw new Error(error.detail || 'Failed to initiate password reset');
      }

      return response.json();
    } catch (error) {
      console.error('❌ Forgot password error:', error);
      throw error;
    }
  }

  async resetPassword(data: { username: string; confirmation_code: string; new_password: string }): Promise<{ message: string }> {
    console.log('🔐 Resetting password...');

    try {
      const response = await this.fetchWithTimeout(`${API_URL}/auth/reset-password`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      }, 15000);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to reset password' }));
        throw new Error(error.detail || 'Failed to reset password');
      }

      return response.json();
    } catch (error) {
      console.error('❌ Reset password error:', error);
      throw error;
    }
  }

  async completeNewPassword(data: { username: string; temporary_password: string; new_password: string }): Promise<AuthResponse> {
    console.log('🔐 Completing new password challenge...');

    try {
      const response = await this.fetchWithTimeout(`${API_URL}/auth/complete-new-password`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      }, 15000);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to complete password setup' }));
        throw new Error(error.detail || 'Failed to complete password setup');
      }

      return response.json();
    } catch (error) {
      console.error('❌ Complete new password error:', error);
      throw error;
    }
  }

  async getCurrentUser(): Promise<User> {
    const response = await fetch(`${API_URL}/auth/me`, {
      headers: this.getAuthHeader(),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Failed to fetch user' }));
      throw new Error(error.detail || 'Failed to fetch user');
    }

    return response.json();
  }

  async getUserInfo(): Promise<{ username: string; attributes: any }> {
    console.log('👤 Fetching user info...');

    try {
      const response = await this.fetchWithTimeout(`${API_URL}/auth/user-info`, {
        method: 'GET',
        headers: this.getAuthHeader(),
      }, 15000);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to fetch user info' }));
        throw new Error(error.detail || 'Failed to fetch user info');
      }

      const result = await response.json();
      console.log('✅ User info fetched:', result);
      return result;
    } catch (error) {
      console.error('❌ Get user info error:', error);
      throw error;
    }
  }

  async uploadImage(file: File, customerId?: string): Promise<UploadResponse> {
    const formData = new FormData();
    formData.append('file', file);

    try {
      const url = new URL(`${API_URL}/images/upload`);
      if (customerId) {
        url.searchParams.append('customer_id', customerId);
      }

      const response = await fetch(url.toString(), {
        method: 'POST',
        headers: this.getAuthHeader(),
        body: formData,
      });

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Upload failed' }));
        throw new Error(error.detail || 'Upload failed');
      }

      return response.json();
    } catch (error) {
      if (error instanceof TypeError && error.message.includes('Invalid URL')) {
        throw new Error(`Invalid API URL configuration: ${API_URL}. Please check NEXT_PUBLIC_API_URL environment variable.`);
      }
      throw error;
    }
  }

  async listImages(prefix?: string): Promise<ListImagesResponse> {
    try {
      const url = new URL(`${API_URL}/images/list`);
      if (prefix) {
        url.searchParams.append('prefix', prefix);
      }

      const response = await fetch(url.toString(), {
        headers: this.getAuthHeader(),
      });

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to fetch images' }));
        throw new Error(error.detail || 'Failed to fetch images');
      }

      const data = await response.json();

      // Transform the response to map presigned_url to url
      // Also validate and sanitize URLs
      if (data.images) {
        data.images = data.images.map((img: BackendImageMetadata) => {
          let url = img.presigned_url || '';

          // Validate URL format
          if (url && !url.startsWith('http://') && !url.startsWith('https://')) {
            console.warn(`Invalid URL format for image ${img.key}:`, url);
            url = '';
          }

          // Force HTTPS if HTTP
          if (url.startsWith('http://')) {
            url = url.replace('http://', 'https://');
          }

          return {
            ...img,
            url,
          };
        });
      }

      return data;
    } catch (error) {
      if (error instanceof TypeError && error.message.includes('Invalid URL')) {
        throw new Error(`Invalid API URL configuration: ${API_URL}. Please check NEXT_PUBLIC_API_URL environment variable.`);
      }
      throw error;
    }
  }

  async deleteImage(key: string): Promise<DeleteResponse> {
    const response = await fetch(`${API_URL}/images/${key}`, {
      method: 'DELETE',
      headers: this.getAuthHeader(),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ detail: 'Delete failed' }));
      throw new Error(error.detail || 'Delete failed');
    }

    return response.json();
  }

  // Customer Management Methods (Admin Only)

  async createCustomer(data: CreateCustomerRequest): Promise<CustomerProfile> {
    console.log('👥 Creating customer...');

    try {
      const response = await this.fetchWithTimeout(`${API_URL}/customers`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...this.getAuthHeader(),
        },
        body: JSON.stringify(data),
      }, 15000);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to create customer' }));
        throw new Error(error.detail || 'Failed to create customer');
      }

      const result = await response.json();
      console.log('✅ Customer created - raw response:', result);

      // Transform response to ensure customer_id is present
      const customer: CustomerProfile = {
        customer_id: result.customer_id || result.id || result.customerId || '',
        email: result.email || '',
        name: result.name || '',
        phone_number: result.phone_number || result.phoneNumber,
        customer_folder: result.customer_folder || result.folder || `customers/${result.customer_id || result.id}`,
        created_date: result.created_date || result.createdDate || result.created_at || new Date().toISOString(),
        enabled: result.enabled !== undefined ? result.enabled : true,
      };

      console.log('✅ Customer created - transformed:', customer.customer_id);
      return customer;
    } catch (error) {
      console.error('❌ Create customer error:', error);
      throw error;
    }
  }

  async listCustomers(limit: number = 60): Promise<CustomerListResponse> {
    console.log('👥 Listing customers...');

    try {
      const url = new URL(`${API_URL}/customers`);
      url.searchParams.append('limit', limit.toString());

      const response = await this.fetchWithTimeout(url.toString(), {
        method: 'GET',
        headers: this.getAuthHeader(),
      }, 15000);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to fetch customers' }));
        throw new Error(error.detail || 'Failed to fetch customers');
      }

      const result = await response.json();
      console.log('✅ Customers fetched:', result.count);

      // Log first customer to debug field names
      if (result.customers && result.customers.length > 0) {
        console.log('📋 Sample customer data:', result.customers[0]);
      }

      // Transform response to ensure customer_id is present
      // Backend might return different field names
      if (result.customers) {
        result.customers = result.customers.map((customer: any) => ({
          customer_id: customer.customer_id || customer.id || customer.customerId || '',
          email: customer.email || '',
          name: customer.name || '',
          phone_number: customer.phone_number || customer.phoneNumber,
          customer_folder: customer.customer_folder || customer.folder || `customers/${customer.customer_id || customer.id}`,
          created_date: customer.created_date || customer.createdDate || customer.created_at || new Date().toISOString(),
          enabled: customer.enabled !== undefined ? customer.enabled : true,
        }));
      }

      return result;
    } catch (error) {
      console.error('❌ List customers error:', error);
      throw error;
    }
  }

  async getCustomer(customerId: string): Promise<CustomerProfile> {
    console.log('👥 Fetching customer:', customerId);

    try {
      const response = await this.fetchWithTimeout(`${API_URL}/customers/${customerId}`, {
        method: 'GET',
        headers: this.getAuthHeader(),
      }, 15000);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to fetch customer' }));
        throw new Error(error.detail || 'Failed to fetch customer');
      }

      const result = await response.json();
      console.log('✅ Customer fetched - raw response:', result);

      // Transform response to ensure customer_id is present
      const customer: CustomerProfile = {
        customer_id: result.customer_id || result.id || result.customerId || customerId,
        email: result.email || '',
        name: result.name || '',
        phone_number: result.phone_number || result.phoneNumber,
        customer_folder: result.customer_folder || result.folder || `customers/${result.customer_id || result.id || customerId}`,
        created_date: result.created_date || result.createdDate || result.created_at || new Date().toISOString(),
        enabled: result.enabled !== undefined ? result.enabled : true,
      };

      return customer;
    } catch (error) {
      console.error('❌ Get customer error:', error);
      throw error;
    }
  }

  async updateCustomer(customerId: string, data: UpdateCustomerRequest): Promise<CustomerProfile> {
    console.log('👥 Updating customer:', customerId);

    try {
      const response = await this.fetchWithTimeout(`${API_URL}/customers/${customerId}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          ...this.getAuthHeader(),
        },
        body: JSON.stringify(data),
      }, 15000);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to update customer' }));
        throw new Error(error.detail || 'Failed to update customer');
      }

      const result = await response.json();
      console.log('✅ Customer updated:', result.customer_id);
      return result;
    } catch (error) {
      console.error('❌ Update customer error:', error);
      throw error;
    }
  }

  async resendWelcomeEmail(customerId: string): Promise<{
    customer_id: string;
    email: string;
    temporary_password: string;
    message: string
  }> {
    console.log('📧 Resending welcome email for customer:', customerId);

    try {
      const response = await this.fetchWithTimeout(`${API_URL}/customers/${customerId}/resend-welcome`, {
        method: 'POST',
        headers: this.getAuthHeader(),
      }, 15000);

      if (!response.ok) {
        const error = await response.json().catch(() => ({ detail: 'Failed to resend welcome email' }));
        throw new Error(error.detail || 'Failed to resend welcome email');
      }

      const result = await response.json();
      console.log('✅ Welcome email resent:', result.message);
      return result;
    } catch (error) {
      console.error('❌ Resend welcome email error:', error);
      throw error;
    }
  }
}

export const api = new ApiClient();

